export const DOMAIN_ROADMAPS = {
  cloud: {
    domain: 'cloud',
    name: 'Cloud Computing',
    tagline: 'Build the infrastructure the world runs on.',
    salary: {
      entry: '₹4–6 LPA',
      mid: '₹10–18 LPA',
      senior: '₹22–40 LPA',
      timeToJobReady: '4–6 months',
      difficulty: 3,
      fastTrack: true,
    },
    phases: [
      {
        number: 1,
        title: 'Foundation',
        duration: '4–6 weeks',
        description: 'Learn Linux fundamentals, basic networking (TCP/IP, DNS, HTTP), and command line fluency. Set up a home lab or use free-tier cloud accounts.',
        tasks: [
          'Complete Linux basics course',
          'Understand TCP/IP, DNS, HTTP protocols',
          'Set up AWS/Azure/GCP free tier account',
          'Practice 20+ CLI commands daily',
        ],
      },
      {
        number: 2,
        title: 'Core Cloud',
        duration: '6–8 weeks',
        description: 'Pick one cloud provider (AWS recommended for jobs in India). Learn compute (EC2), storage (S3), networking (VPC), and IAM. Deploy a real app.',
        tasks: [
          'Master EC2, S3, VPC, IAM on AWS',
          'Deploy a 3-tier web application',
          'Learn Infrastructure as Code (Terraform basics)',
          'Understand cloud pricing and cost optimization',
        ],
      },
      {
        number: 3,
        title: 'DevOps & Automation',
        duration: '6–8 weeks',
        description: 'Learn Docker, CI/CD pipelines, and basic Kubernetes. Automate deployments. This is where you become employable.',
        tasks: [
          'Containerize applications with Docker',
          'Build CI/CD pipelines (GitHub Actions or Jenkins)',
          'Deploy to Kubernetes (EKS/AKS)',
          'Write automation scripts (Bash/Python)',
        ],
      },
      {
        number: 4,
        title: 'Security & Monitoring',
        duration: '4–6 weeks',
        description: 'Cloud security best practices, monitoring with CloudWatch/Prometheus, logging, and incident response basics.',
        tasks: [
          'Implement cloud security best practices',
          'Set up monitoring and alerting',
          'Learn log aggregation and analysis',
          'Practice incident response scenarios',
        ],
      },
      {
        number: 5,
        title: 'Specialize & Certify',
        duration: '4–6 weeks',
        description: 'Get certified, build a portfolio of 3 real projects, and start applying. Pick a specialization: DevOps, Solutions Architecture, or Cloud Security.',
        tasks: [
          'Pass AWS Solutions Architect Associate',
          'Build 3 portfolio projects with documentation',
          'Contribute to open-source cloud tools',
          'Start applying and networking on LinkedIn',
        ],
      },
    ],
    certifications: [
      { name: 'AWS Solutions Architect – Associate', priority: 2, link: 'https://aws.amazon.com/certification/certified-solutions-architect-associate/' },
      { name: 'AWS Cloud Practitioner', priority: 1, link: 'https://aws.amazon.com/certification/certified-cloud-practitioner/' },
      { name: 'Terraform Associate', priority: 1, link: 'https://www.hashicorp.com/certification/terraform-associate' },
      { name: 'CKA (Kubernetes)', priority: 1, link: 'https://training.linuxfoundation.org/certification/certified-kubernetes-administrator-cka/' },
    ],
    nextStep: {
      text: 'Create a free AWS account and launch your first EC2 instance. Follow the AWS Getting Started guide — it takes 20 minutes.',
      link: 'https://aws.amazon.com/getting-started/',
    },
  },

  fullstack: {
    domain: 'fullstack',
    name: 'Full Stack Development',
    tagline: 'Build what people use. Ship what matters.',
    salary: {
      entry: '₹4–8 LPA',
      mid: '₹12–22 LPA',
      senior: '₹25–50 LPA',
      timeToJobReady: '5–7 months',
      difficulty: 3,
      fastTrack: true,
    },
    phases: [
      {
        number: 1,
        title: 'Frontend Foundations',
        duration: '4–6 weeks',
        description: 'Master HTML, CSS, and JavaScript fundamentals. Build 5 small projects. Focus on responsive design and DOM manipulation.',
        tasks: [
          'Build 5 responsive web pages from scratch',
          'Master CSS Flexbox and Grid',
          'JavaScript fundamentals: ES6+, async/await, DOM',
          'Version control with Git and GitHub',
        ],
      },
      {
        number: 2,
        title: 'React & Modern Frontend',
        duration: '6–8 weeks',
        description: 'Learn React deeply — components, hooks, state management, routing. Build 2 real applications. Learn Tailwind CSS.',
        tasks: [
          'React fundamentals: components, hooks, context',
          'React Router for navigation',
          'State management patterns',
          'Build 2 complete React applications',
        ],
      },
      {
        number: 3,
        title: 'Backend & Databases',
        duration: '6–8 weeks',
        description: 'Node.js + Express for APIs. PostgreSQL or MongoDB for data. Authentication, file uploads, email — real backend skills.',
        tasks: [
          'Build REST APIs with Node.js + Express',
          'Database design and queries (PostgreSQL)',
          'Authentication with JWT and sessions',
          'File uploads, email integration, payments',
        ],
      },
      {
        number: 4,
        title: 'Full Stack Integration',
        duration: '4–6 weeks',
        description: 'Connect frontend and backend. Deploy to production. Learn Docker basics, CI/CD, and monitoring.',
        tasks: [
          'Build and deploy a complete full-stack app',
          'Docker basics for local development',
          'Deploy to Vercel/Railway/Render',
          'Set up CI/CD with GitHub Actions',
        ],
      },
      {
        number: 5,
        title: 'Portfolio & Job Prep',
        duration: '4–6 weeks',
        description: 'Build 3 portfolio-worthy projects. Practice DSA for interviews. Optimize your GitHub and LinkedIn profiles.',
        tasks: [
          'Ship 3 complete portfolio projects',
          'Practice top 100 DSA problems',
          'Optimize GitHub profile and README files',
          'Apply to 20+ companies, track responses',
        ],
      },
    ],
    certifications: [
      { name: 'Meta Frontend Developer Certificate', priority: 2, link: 'https://www.coursera.org/professional-certificates/meta-front-end-developer' },
      { name: 'freeCodeCamp Full Stack', priority: 1, link: 'https://www.freecodecamp.org/' },
      { name: 'AWS Cloud Practitioner', priority: 1, link: 'https://aws.amazon.com/certification/certified-cloud-practitioner/' },
    ],
    nextStep: {
      text: 'Open VS Code, create a new folder, and build a personal portfolio page with HTML and CSS. Deploy it to GitHub Pages in under an hour.',
      link: 'https://pages.github.com/',
    },
  },

  data: {
    domain: 'data',
    name: 'Data Analytics',
    tagline: 'Find the truth hiding in the numbers.',
    salary: {
      entry: '₹4–7 LPA',
      mid: '₹10–18 LPA',
      senior: '₹20–35 LPA',
      timeToJobReady: '3–5 months',
      difficulty: 2,
      fastTrack: true,
    },
    phases: [
      {
        number: 1,
        title: 'Data Foundations',
        duration: '3–4 weeks',
        description: 'Excel power features, basic statistics, and data thinking. Learn to ask the right questions before touching any tool.',
        tasks: [
          'Master Excel: pivot tables, VLOOKUP, charts',
          'Basic statistics: mean, median, standard deviation',
          'Learn to frame business questions as data problems',
          'Explore 3 real-world datasets manually',
        ],
      },
      {
        number: 2,
        title: 'SQL & Databases',
        duration: '4–5 weeks',
        description: 'SQL is non-negotiable. Write complex queries, joins, subqueries, window functions. Practice on real databases.',
        tasks: [
          'SQL fundamentals: SELECT, JOIN, GROUP BY',
          'Advanced SQL: window functions, CTEs, subqueries',
          'Practice on HackerRank/LeetCode SQL challenges',
          'Design a simple database schema',
        ],
      },
      {
        number: 3,
        title: 'Python for Analysis',
        duration: '5–6 weeks',
        description: 'Python + Pandas + NumPy for data manipulation. Matplotlib/Seaborn for visualization. Jupyter notebooks for workflow.',
        tasks: [
          'Python basics: data types, loops, functions',
          'Pandas: data cleaning, merging, aggregation',
          'Visualization with Matplotlib and Seaborn',
          'Complete 3 end-to-end analysis projects',
        ],
      },
      {
        number: 4,
        title: 'BI Tools & Dashboards',
        duration: '3–4 weeks',
        description: 'Power BI or Tableau. Build interactive dashboards. Learn to tell a data story that drives business decisions.',
        tasks: [
          'Build 5 dashboards in Power BI or Tableau',
          'Learn data storytelling principles',
          'Connect to live data sources',
          'Present insights to a non-technical audience',
        ],
      },
      {
        number: 5,
        title: 'Portfolio & Certify',
        duration: '3–4 weeks',
        description: 'Build a portfolio of 4 data projects published on GitHub. Get certified. Start applying to analyst roles.',
        tasks: [
          'Publish 4 data analysis projects on GitHub',
          'Pass Google Data Analytics Certificate',
          'Write case studies for each project',
          'Apply to 15+ data analyst positions',
        ],
      },
    ],
    certifications: [
      { name: 'Google Data Analytics Certificate', priority: 2, link: 'https://www.coursera.org/professional-certificates/google-data-analytics' },
      { name: 'Microsoft Power BI Data Analyst', priority: 2, link: 'https://learn.microsoft.com/en-us/certifications/power-bi-data-analyst-associate/' },
      { name: 'IBM Data Analyst', priority: 1, link: 'https://www.coursera.org/professional-certificates/ibm-data-analyst' },
    ],
    nextStep: {
      text: 'Download a free dataset from Kaggle (try "Superstore Sales") and open it in Google Sheets. Find 3 interesting patterns in 30 minutes.',
      link: 'https://www.kaggle.com/datasets',
    },
  },

  ai: {
    domain: 'ai',
    name: 'AI & Machine Learning',
    tagline: 'Teach machines to see patterns humans can\'t.',
    salary: {
      entry: '₹6–10 LPA',
      mid: '₹15–28 LPA',
      senior: '₹30–60 LPA',
      timeToJobReady: '8–14 months',
      difficulty: 4,
      fastTrack: false,
    },
    phases: [
      {
        number: 1,
        title: 'Math & Python',
        duration: '6–8 weeks',
        description: 'Linear algebra, probability, statistics, and calculus fundamentals. Python programming with NumPy, Pandas, Matplotlib.',
        tasks: [
          'Linear algebra: vectors, matrices, eigenvalues',
          'Probability and statistics review',
          'Python: NumPy, Pandas, Matplotlib mastery',
          'Complete 3Blue1Brown linear algebra series',
        ],
      },
      {
        number: 2,
        title: 'Core ML',
        duration: '8–10 weeks',
        description: 'Supervised/unsupervised learning. Regression, classification, clustering. Scikit-learn. Feature engineering. Model evaluation.',
        tasks: [
          'Implement regression and classification algorithms',
          'Learn scikit-learn thoroughly',
          'Feature engineering and selection techniques',
          'Model evaluation: cross-validation, metrics',
        ],
      },
      {
        number: 3,
        title: 'Deep Learning',
        duration: '8–10 weeks',
        description: 'Neural networks, CNNs, RNNs, Transformers. TensorFlow or PyTorch. Train models on real datasets.',
        tasks: [
          'Build neural networks from scratch',
          'Master PyTorch or TensorFlow',
          'CNN for image tasks, RNN for sequences',
          'Fine-tune pre-trained models',
        ],
      },
      {
        number: 4,
        title: 'Specialization',
        duration: '6–8 weeks',
        description: 'Pick: NLP, Computer Vision, or Generative AI. Build 3 specialized projects. Learn MLOps basics.',
        tasks: [
          'Choose a specialization and go deep',
          'Build 3 projects in your specialization',
          'Learn model deployment (FastAPI, Docker)',
          'MLOps basics: experiment tracking, versioning',
        ],
      },
      {
        number: 5,
        title: 'Research & Apply',
        duration: '6–8 weeks',
        description: 'Read and implement 3 research papers. Build an end-to-end ML product. Start applying to ML engineer roles.',
        tasks: [
          'Read and implement 3 ML research papers',
          'Build and deploy an end-to-end ML product',
          'Publish projects on GitHub with documentation',
          'Apply to ML engineer / Data scientist roles',
        ],
      },
    ],
    certifications: [
      { name: 'Andrew Ng ML Specialization (Stanford)', priority: 2, link: 'https://www.coursera.org/specializations/machine-learning-introduction' },
      { name: 'Deep Learning Specialization', priority: 2, link: 'https://www.coursera.org/specializations/deep-learning' },
      { name: 'TensorFlow Developer Certificate', priority: 1, link: 'https://www.tensorflow.org/certificate' },
    ],
    nextStep: {
      text: 'Start Andrew Ng\'s Machine Learning course on Coursera. Watch the first 3 videos today — they\'re free and will change how you see data.',
      link: 'https://www.coursera.org/specializations/machine-learning-introduction',
    },
  },

  cyber: {
    domain: 'cyber',
    name: 'Cybersecurity',
    tagline: 'Protect what everyone else forgets to.',
    salary: {
      entry: '₹4–7 LPA',
      mid: '₹12–22 LPA',
      senior: '₹25–50 LPA',
      timeToJobReady: '5–8 months',
      difficulty: 4,
      fastTrack: false,
    },
    phases: [
      {
        number: 1,
        title: 'Foundations',
        duration: '4–6 weeks',
        description: 'Networking fundamentals (TCP/IP, DNS, firewalls), Linux command line, and basic security concepts. Set up a home lab.',
        tasks: [
          'Master TCP/IP, DNS, HTTP/S, firewalls',
          'Linux command line proficiency',
          'Set up a virtual lab (VirtualBox + Kali)',
          'Learn CIA triad and security fundamentals',
        ],
      },
      {
        number: 2,
        title: 'Offensive Security',
        duration: '6–8 weeks',
        description: 'Ethical hacking basics. Learn to think like an attacker. OWASP Top 10, vulnerability scanning, basic exploitation.',
        tasks: [
          'OWASP Top 10 vulnerabilities in depth',
          'Practice on TryHackMe and HackTheBox',
          'Learn Burp Suite, Nmap, Metasploit basics',
          'Complete 20 CTF challenges',
        ],
      },
      {
        number: 3,
        title: 'Defensive Security',
        duration: '6–8 weeks',
        description: 'SOC operations, SIEM tools, incident response, log analysis. Learn to detect and respond to real threats.',
        tasks: [
          'Set up and configure a SIEM (Splunk/ELK)',
          'Log analysis and threat detection',
          'Incident response procedures',
          'Network traffic analysis with Wireshark',
        ],
      },
      {
        number: 4,
        title: 'Compliance & Governance',
        duration: '4–6 weeks',
        description: 'Security frameworks (NIST, ISO 27001), risk assessment, compliance basics. This is what makes you hireable in India.',
        tasks: [
          'Learn NIST and ISO 27001 frameworks',
          'Risk assessment methodologies',
          'Security policy documentation',
          'Audit and compliance processes',
        ],
      },
      {
        number: 5,
        title: 'Certify & Specialize',
        duration: '4–6 weeks',
        description: 'Get CompTIA Security+ or CEH. Build a security portfolio. Pick: pentesting, SOC analysis, or GRC.',
        tasks: [
          'Pass CompTIA Security+ or CEH',
          'Build a cybersecurity portfolio/blog',
          'Contribute to bug bounty programs',
          'Apply to SOC analyst / security analyst roles',
        ],
      },
    ],
    certifications: [
      { name: 'CompTIA Security+', priority: 2, link: 'https://www.comptia.org/certifications/security' },
      { name: 'CEH (Certified Ethical Hacker)', priority: 2, link: 'https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/' },
      { name: 'CompTIA Network+', priority: 1, link: 'https://www.comptia.org/certifications/network' },
    ],
    nextStep: {
      text: 'Create a free TryHackMe account and complete the "Pre-Security" learning path. It takes about 2 hours and needs zero experience.',
      link: 'https://tryhackme.com/',
    },
  },

  design: {
    domain: 'design',
    name: 'UI/UX Design',
    tagline: 'Make technology feel human.',
    salary: {
      entry: '₹3–6 LPA',
      mid: '₹8–16 LPA',
      senior: '₹18–35 LPA',
      timeToJobReady: '4–6 months',
      difficulty: 2,
      fastTrack: true,
    },
    phases: [
      {
        number: 1,
        title: 'Design Fundamentals',
        duration: '3–4 weeks',
        description: 'Visual design principles: typography, color theory, layout, spacing. Study 50 great interfaces. Develop your eye.',
        tasks: [
          'Study typography, color theory, layout principles',
          'Analyze 50 well-designed interfaces',
          'Learn Gestalt principles of design',
          'Practice daily UI design challenges',
        ],
      },
      {
        number: 2,
        title: 'UX Research & Process',
        duration: '4–5 weeks',
        description: 'User research methods, personas, user journeys, information architecture, wireframing. Think before you design.',
        tasks: [
          'Learn user research methods: interviews, surveys',
          'Create personas and user journey maps',
          'Information architecture and card sorting',
          'Wireframing: low-fi to high-fi process',
        ],
      },
      {
        number: 3,
        title: 'Figma Mastery',
        duration: '5–6 weeks',
        description: 'Figma is industry standard. Learn components, auto-layout, design systems, prototyping, and collaboration features.',
        tasks: [
          'Master Figma: components, auto-layout, variants',
          'Build a complete design system from scratch',
          'Create interactive prototypes',
          'Learn handoff tools and developer collaboration',
        ],
      },
      {
        number: 4,
        title: 'Portfolio Projects',
        duration: '4–5 weeks',
        description: 'Design 3 complete projects end-to-end: research → wireframes → high-fi → prototype → case study.',
        tasks: [
          'Complete 3 end-to-end design projects',
          'Write detailed UX case studies',
          'Include user research in every project',
          'Get feedback from design communities',
        ],
      },
      {
        number: 5,
        title: 'Polish & Apply',
        duration: '3–4 weeks',
        description: 'Build your portfolio website. Learn basic frontend (HTML/CSS) to stand out. Apply to UI/UX roles.',
        tasks: [
          'Build a portfolio website showcasing case studies',
          'Learn HTML/CSS basics for designer credibility',
          'Google UX Design Certificate (if not done)',
          'Apply to 15+ design positions',
        ],
      },
    ],
    certifications: [
      { name: 'Google UX Design Certificate', priority: 2, link: 'https://www.coursera.org/professional-certificates/google-ux-design' },
      { name: 'Interaction Design Foundation', priority: 1, link: 'https://www.interaction-design.org/' },
      { name: 'Meta Front-End Developer', priority: 1, link: 'https://www.coursera.org/professional-certificates/meta-front-end-developer' },
    ],
    nextStep: {
      text: 'Open Figma (free), pick any app on your phone, and redesign one screen. Post it on Dribbble. That\'s your first portfolio piece.',
      link: 'https://www.figma.com/',
    },
  },

  networking: {
    domain: 'networking',
    name: 'Networking',
    tagline: 'Connect everything. Secure everything.',
    salary: {
      entry: '₹3–5 LPA',
      mid: '₹8–15 LPA',
      senior: '₹18–30 LPA',
      timeToJobReady: '4–6 months',
      difficulty: 3,
      fastTrack: true,
    },
    phases: [
      {
        number: 1,
        title: 'Network Basics',
        duration: '4–5 weeks',
        description: 'OSI model, TCP/IP, subnetting, DNS, DHCP. Use Packet Tracer for hands-on practice. This is the language of networking.',
        tasks: [
          'Master OSI model and TCP/IP stack',
          'Subnetting: CIDR, VLSM calculations',
          'DNS, DHCP, ARP — how they actually work',
          'Set up Cisco Packet Tracer and practice',
        ],
      },
      {
        number: 2,
        title: 'Routing & Switching',
        duration: '6–8 weeks',
        description: 'Cisco IOS, VLANs, spanning tree, OSPF, EIGRP. Configure real network topologies in Packet Tracer and GNS3.',
        tasks: [
          'Configure VLANs and inter-VLAN routing',
          'Implement OSPF and EIGRP protocols',
          'Spanning Tree Protocol configurations',
          'Build complex topologies in GNS3',
        ],
      },
      {
        number: 3,
        title: 'Network Security',
        duration: '4–6 weeks',
        description: 'Firewalls, ACLs, VPNs, NAT. Network security is where networking meets cybersecurity — highly employable intersection.',
        tasks: [
          'Configure ACLs and firewall rules',
          'Set up VPN tunnels (IPsec, SSL)',
          'NAT and PAT configurations',
          'Network security best practices',
        ],
      },
      {
        number: 4,
        title: 'Cloud Networking',
        duration: '4–5 weeks',
        description: 'AWS VPC, Azure networking, hybrid networks. Modern networking is cloud networking. This is the growth area.',
        tasks: [
          'AWS VPC: subnets, route tables, gateways',
          'Azure networking fundamentals',
          'Hybrid network architectures',
          'Software-defined networking concepts',
        ],
      },
      {
        number: 5,
        title: 'Certify & Apply',
        duration: '4–5 weeks',
        description: 'Pass CCNA — the gold standard for networking careers in India. Build a home lab portfolio. Apply.',
        tasks: [
          'Pass Cisco CCNA certification',
          'Document home lab configurations',
          'Build a networking portfolio/blog',
          'Apply to network engineer positions',
        ],
      },
    ],
    certifications: [
      { name: 'Cisco CCNA', priority: 2, link: 'https://www.cisco.com/site/us/en/learn/training-certifications/certifications/enterprise/ccna/index.html' },
      { name: 'CompTIA Network+', priority: 2, link: 'https://www.comptia.org/certifications/network' },
      { name: 'AWS Advanced Networking', priority: 1, link: 'https://aws.amazon.com/certification/certified-advanced-networking-specialty/' },
    ],
    nextStep: {
      text: 'Download Cisco Packet Tracer (free with Netacad account) and build your first network: 2 PCs, 1 switch, 1 router. Make them ping each other.',
      link: 'https://www.netacad.com/courses/packet-tracer',
    },
  },

  business: {
    domain: 'business',
    name: 'Business & Product Management',
    tagline: 'Build what the market actually needs.',
    salary: {
      entry: '₹4–7 LPA',
      mid: '₹12–22 LPA',
      senior: '₹25–50 LPA',
      timeToJobReady: '4–6 months',
      difficulty: 2,
      fastTrack: true,
    },
    phases: [
      {
        number: 1,
        title: 'Business Thinking',
        duration: '3–4 weeks',
        description: 'Business models, market analysis, competitive research. Learn to think about problems from a business perspective.',
        tasks: [
          'Study 20 business models (SaaS, marketplace, etc.)',
          'Learn market sizing (TAM, SAM, SOM)',
          'Competitive analysis frameworks',
          'Read "Inspired" by Marty Cagan',
        ],
      },
      {
        number: 2,
        title: 'Product Management',
        duration: '5–6 weeks',
        description: 'Product lifecycle, user stories, PRDs, roadmapping, prioritization frameworks (RICE, MoSCoW). The art of deciding what to build.',
        tasks: [
          'Write user stories and PRDs',
          'Learn RICE and MoSCoW prioritization',
          'Build a product roadmap for a real product',
          'Practice stakeholder communication',
        ],
      },
      {
        number: 3,
        title: 'Data & Analytics',
        duration: '4–5 weeks',
        description: 'SQL basics, Google Analytics, product metrics (DAU, retention, funnel analysis). Data-informed decision making.',
        tasks: [
          'SQL basics for product managers',
          'Google Analytics and Mixpanel setup',
          'Define and track product KPIs',
          'A/B testing fundamentals',
        ],
      },
      {
        number: 4,
        title: 'Tech Literacy',
        duration: '3–4 weeks',
        description: 'Understand APIs, databases, basic system design. You don\'t need to code, but you need to speak the language.',
        tasks: [
          'Understand REST APIs and system architecture',
          'Basic database concepts and data modeling',
          'Read technical documentation critically',
          'Practice technical communication with engineers',
        ],
      },
      {
        number: 5,
        title: 'Portfolio & Apply',
        duration: '3–4 weeks',
        description: 'Build a PM portfolio with 3 case studies. Practice PM interviews (product sense, metrics, estimation). Apply.',
        tasks: [
          'Write 3 detailed PM case studies',
          'Practice product sense interview questions',
          'Mock interviews with peers/mentors',
          'Apply to APM/PM positions at startups',
        ],
      },
    ],
    certifications: [
      { name: 'Google Project Management Certificate', priority: 2, link: 'https://www.coursera.org/professional-certificates/google-project-management' },
      { name: 'Product School PM Certificate', priority: 1, link: 'https://productschool.com/' },
      { name: 'Google Data Analytics Certificate', priority: 1, link: 'https://www.coursera.org/professional-certificates/google-data-analytics' },
    ],
    nextStep: {
      text: 'Pick any app you use daily. Write a 1-page product teardown: what it does well, what\'s broken, and one feature you\'d build next. Post it on LinkedIn.',
      link: 'https://www.lennysnewsletter.com/',
    },
  },
};
